### ISSUE TITLE
crash after update to 5.2.1

### ISSUE THREAD

**Issue by fuzzblob** [KiARC/Sobriety#32]
Just updated via F-Droid and got this error when attempting to launch the app.

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.220905.004.A1/2022091400:user/release-keys
package: com.katiearose.sobriety:12
process: com.katiearose.sobriety

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.katiearose.sobriety/com.katiearose.sobriety.Main}: java.io.InvalidClassException: m1.a; class invalid for deserialization
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3677)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.io.InvalidClassException: m1.a; class invalid for deserialization
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:154)
	at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:798)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1901)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1440)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
	at java.util.ArrayList.readObject(ArrayList.java:791)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2041)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1927)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1440)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
	at n1.e.a(Unknown Source:105)
	at com.katiearose.sobriety.Main.onCreate(Unknown Source:88)
	at android.app.Activity.performCreate(Activity.java:8301)
	at android.app.Activity.performCreate(Activity.java:8280)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1389)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
	... 14 more

```

**Comment by KiARC** [comment]
Hmm... It seems like an error caused by reading an outdated cache? Try clearing app data to check? If so that sucks and I'm sorry, if not I'm really not sure as I haven't been able to reproduce this.

**Comment by fuzzblob** [comment]
Yeah. After clearing the data and putting my entries back in its all good :)

**Comment by KiARC** [comment]
Just curious what did you update from?

**Comment by KiARC** [comment]
If it was more than two versions old the cache wouldn't be readable

**Comment by fuzzblob** [comment]
I'm not sure but I believe v5.1.5
