### ISSUE TITLE
App crashes Immediately after v8.0.0 update

### ISSUE THREAD

**Issue by IRanOutOfIdeasForMyUsername** [KiARC/Sobriety#69]
I just updated to v8.0.0 from v7.0.0 and now I can't even open the app. All is does is crash on me.

**Comment by JacobOB1234** [comment]
Same here. Device is pixel 4a. This is the error log :

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ1A.230105.001/2023010300:user/release-keys
package: com.katiearose.sobriety:19
process: com.katiearose.sobriety
processUptime: 460 + 996 ms

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.katiearose.sobriety/com.katiearose.sobriety.activities.Main}: java.io.InvalidClassException: j$.time.s; class invalid for deserialization
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.io.InvalidClassException: j$.time.s; class invalid for deserialization
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:154)
	at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:798)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1901)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1440)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
	at java.util.HashMap.readObject(HashMap.java:1408)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2041)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1927)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1440)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
	at java.util.ArrayList.readObject(ArrayList.java:791)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2041)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1927)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1440)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
	at j1.a.a(Unknown Source:105)
	at com.katiearose.sobriety.activities.Main.onCreate(Unknown Source:148)
	at android.app.Activity.performCreate(Activity.java:8352)
	at android.app.Activity.performCreate(Activity.java:8331)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1422)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
	... 14 more

```

**Comment by sadellie** [comment]
Duplicate of #68
Clear app data.

P.S. it's kinda insane that this bug is occurring almost every update.

**Comment by IRanOutOfIdeasForMyUsername** [comment]
Thanks, that worked, though it's really annoying that I have to re-setup everything.

**Comment by KiARC** [comment]
I'm so sorry, this has been in my to-do list for a long time I just haven't had the time to work on much recently with some stuff that's been happening, I'm going to fix it as soon as I'm able to

**Comment by IRanOutOfIdeasForMyUsername** [comment]
Don't beat yourself up too much about it, we all have a certain something in our lives that we put off now and again.

**Comment by IRanOutOfIdeasForMyUsername** [comment]
> I know I just hate that my mental health is getting in the way of development, I really care about this project and I feel like it doesn't seem that way to anyone else

As hard as this life is, there comes a point when you have to stop caring about what others think. You're an amazing person for having done so much already, and no one has the right to claim anything otherwise. 

If you can only do so much, then rest easy knowing that you have in the past, and continue  to do all that you can for this project. And despite the flaws, whatever they may be, you've made lives better. Even mine. 

Don't let yourself be defined, even in your own head, by the faults, and follys of the world. 

You deserve so much more than that, and you're worth so much more that.

**Comment by IRanOutOfIdeasForMyUsername** [comment]
> Thank you so much. I really needed that. I'm genuinely so happy that this is sorta taking off but I'd been putting so much into it that I've been burnt out for a while. Hell, I even wrote a paper on the applications of technology in addiction treatment lmao. I'm just glad that I'm able to make a difference, even if I'm slowing down a bit right now.

Just keep doing what you can right now. If that's nothing for a while, then so be it :)

And a paper? That's so cool!

**Comment by avaaum** [comment]
i opened an issue last release and the dev closed it and said it would be taken care of this release. 

i get mental health issues, they are more important than any app. i also understand the frustration of those who have to lose their track record and manually reset everything each release. 

at the end of the day, we support you and we are grateful for the app, but the fact remains, people will stop using it for their own mental and physical health if this issue persists every update. it would be a shame to see that happen. i'm rooting for you!

**Comment by KiARC** [comment]
Its actually fixed now, but unfortunately the fix doesn't work with v8.0.0->v9.0.0. going forwards serialization is done with JSON and it will no longer have this bug in future releases

**Comment by sadellie** [comment]
User data is saved in JSON, right? Will there be a migration strategy in case JSON scheme is changed so no data is lost?

**Comment by KiARC** [comment]
It is starting in v9.0.0 :/
Previous versions serialized various classes with ObjectOutputStreams, which made it so that when anything changed in those classes the cache could no longer be read. That's why an effort is being made to implement JSON exports in previous versions.

Going forwards it'll be fairly easy to implement migration strategies just because of how JSON works; if a cache can't be read, just check whether the previous version's code can read it until you find one that works.
